### ISSUE TITLE
Block texture not rendered in the world (1.12.2)

### ISSUE THREAD

**Issue by Real-Gecko** [Iuhegi/Simple-Cobble-Generator#1]
![2018-02-27_16 15 56](https://user-images.githubusercontent.com/2231969/36723278-03e626d8-1bda-11e8-9cc4-684388f338be.png)

**Comment by Iuhegi** [comment]
Fixed, also added recipe to recipe book and changed the recipe to be a JSON while i was at it :)

**Comment by Real-Gecko** [comment]
Cool!
