### ISSUE TITLE
[Suggestion] Configurable Speed

### ISSUE THREAD

**Issue by TheLimePixel** [Iuhegi/Simple-Cobble-Generator#3]
Could you please add a config option for the speed at which Cobblestone is generated?

**Comment by Iuhegi** [comment]
I could add a config for a production limit but that is about all

**Comment by TheLimePixel** [comment]
Yeah, that's what I meant.

**Comment by Iuhegi** [comment]
Ok, sorted, it is in the latest version available on CurseForge [[link]](https://minecraft.curseforge.com/projects/simplecobblestonegenerator/files/2572889). Thanks for the feedback, it was appreciated.
